services:
  - type: web
    name: super-videotheque-api
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: PAYHIP_API_BASE_URL
        value: https://payhip.com/api/v2
      - key: PAYHIP_API_KEY
        sync: false
      - key: PAYHIP_PRODUCT_ID
        sync: false
      - key: BUNNY_API_KEY
        sync: false
      - key: BUNNY_LIBRARY_ID
        sync: false
      - key: BUNNY_PULL_ZONE_HOST
        sync: false
      - key: BUNNY_SIGNING_KEY
        sync: false
      - key: BUNNY_PUBLIC_LIBRARY_ID
        sync: false
      - key: BUNNY_PUBLIC_PULL_ZONE_HOST
        sync: false
      - key: BUNNY_PUBLIC_API_KEY
        sync: false
      - key: DEFAULT_RENTAL_HOURS
        value: "1"
